#spring.main.allow-circular-references=true

server:
  servlet:
    context-path: /
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always

debug: true

spring:
  output:
    ansi:
      enabled: always
  mvc:
    log-request-details: true
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:C:/Users/FOREVERGWC/IdeaProjects/jee2022_exam/db/
    username: sa
    password:
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    cn:
      jee: debug
    org:
      springframework: debug
      hibernate:
        sql: debug
        jdbc:
          bind: trace
        type:
          descriptor:
            sql: trace
    web: trace
    sql: debug


upload:
  path: C:\\imgs\\
